---
- name: install prometheus
  hosts: roy.local
  become: yes
  become_user: root

  tasks:
  - name: install prometheus package
    apt:
      name: prometheus
      state: latest
  - name: setup prometheus systemd drop-in directory
    file:
      path: /etc/systemd/system/prometheus.service.d
      state: directory
  - name: configure prometheus (point to environment file)
    template:
      dest: /etc/systemd/system/prometheus.service.d/override.conf
      src: systemd-override.conf.j2
    notify: reload daemon config
  - name: configure prometheus (override startup args)
    template:
      dest: /usr/local/etc/prometheus.env
      src: systemd-startup.env
    notify: reload daemon config
  - name: configure prometheus (prometheus settings)
    copy:
      dest: /etc/prometheus/prometheus.yml
      src: prometheus.yml
      owner: prometheus
      mode: "0644"
    notify: reload prometheus
  handlers: 
  - name: reload daemon config
    systemd:
      daemon_reload: yes
  - name: restart prometheus
    service:
      name: prometheus
      state: restarted
  - name: reload prometheus
    service:
      name: prometheus
      state: reloaded
